import json

nft_string = '''
{
    "next": null,
    "previous": null,
    "asset_events": [
        {
            "asset": {
                "id": 18201858,
                "num_sales": 4,
                "background_color": null,
                "image_url": "https://i.seadn.io/gae/KZjKg6hPfsaGC9Ok6IjrmyqkmgS1ZWSOjCHVjWGDw5i9zwnPNrDvePPK44-dZ9tqnzwsnUnQrFWVl_O90D5DpUV3YF6Yrq3CH7xm?w=500&auto=format",
                "image_preview_url": "https://i.seadn.io/gae/KZjKg6hPfsaGC9Ok6IjrmyqkmgS1ZWSOjCHVjWGDw5i9zwnPNrDvePPK44-dZ9tqnzwsnUnQrFWVl_O90D5DpUV3YF6Yrq3CH7xm?w=500&auto=format",
                "image_thumbnail_url": "https://i.seadn.io/gae/KZjKg6hPfsaGC9Ok6IjrmyqkmgS1ZWSOjCHVjWGDw5i9zwnPNrDvePPK44-dZ9tqnzwsnUnQrFWVl_O90D5DpUV3YF6Yrq3CH7xm?w=500&auto=format",
                "image_original_url": "https://ipfs.io/ipfs/QmS8AP7PHk2X3JCe91L2mYNtGwEyGzYUjAsc4Lf6JjfV96/image.gif",
                "animation_url": null,
                "animation_original_url": null,
                "name": "PixaWizard284",
                "description": "One of 1,000 PixaWizards. Made by PixaLyfe.",
                "external_link": "https://app.rarible.com/token/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0:300",
                "asset_contract": {
                    "address": "0xc6b0b290176aaab958441dcb0c64ad057cbc39a0",
                    "asset_contract_type": "non-fungible",
                    "created_date": "2021-02-14T05:14:04.847603",
                    "name": "PixaWizards",
                    "nft_version": "3.0",
                    "opensea_version": null,
                    "owner": 19357952,
                    "schema_name": "ERC721",
                    "symbol": "PWIZ",
                    "total_supply": "0",
                    "description": "A collection of 1,000 unique pixelated wizards.",
                    "external_link": "http://www.pixalyfe.com",
                    "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                    "default_to_fiat": false,
                    "dev_buyer_fee_basis_points": 0,
                    "dev_seller_fee_basis_points": 500,
                    "only_proxied_transfers": false,
                    "opensea_buyer_fee_basis_points": 0,
                    "opensea_seller_fee_basis_points": 250,
                    "buyer_fee_basis_points": 0,
                    "seller_fee_basis_points": 750,
                    "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c"
                },
                "permalink": "https://opensea.io/assets/ethereum/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0/300",
                "collection": {
                    "banner_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                    "chat_url": null,
                    "created_date": "2021-02-17T11:34:32.953650+00:00",
                    "default_to_fiat": false,
                    "description": "A collection of 1,000 unique pixelated wizards.",
                    "dev_buyer_fee_basis_points": "0",
                    "dev_seller_fee_basis_points": "500",
                    "discord_url": "https://discord.gg/invite/mj2uxev38D",
                    "display_data": {
                        "card_display_style": "contain"
                    },
                    "external_url": "http://www.pixalyfe.com",
                    "featured": false,
                    "featured_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                    "hidden": false,
                    "safelist_request_status": "verified",
                    "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                    "is_subject_to_whitelist": false,
                    "large_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                    "medium_username": null,
                    "name": "PixaWizards",
                    "only_proxied_transfers": false,
                    "opensea_buyer_fee_basis_points": "0",
                    "opensea_seller_fee_basis_points": "250",
                    "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c",
                    "require_email": false,
                    "short_description": null,
                    "slug": "pixawizards",
                    "telegram_url": null,
                    "twitter_username": "pixa_nft",
                    "instagram_username": "pixalyfe",
                    "wiki_url": null,
                    "is_nsfw": false,
                    "fees": {
                        "seller_fees": {
                            "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c": 500
                        },
                        "opensea_fees": {
                            "0x0000a26b00c1f0df003000390027140000faa719": 250
                        }
                    },
                    "is_rarity_enabled": true
                },
                "decimals": 0,
                "token_metadata": "https://ipfs.io/ipfs/QmecXEtqWgRpwAXVtyUDPvMkgRBCj1C7wSnra8C8g3bYCJ",
                "is_nsfw": false,
                "owner": null,
                "token_id": "300"
            },
            "asset_bundle": null,
            "event_type": "successful",
            "event_timestamp": "2023-01-04T19:00:59",
            "auction_type": null,
            "total_price": "55000000000000000",
            "payment_token": {
                "symbol": "ETH",
                "address": "0x0000000000000000000000000000000000000000",
                "image_url": "https://openseauserdata.com/files/6f8e2979d428180222796ff4a33ab929.svg",
                "name": "Ether",
                "decimals": 18,
                "eth_price": "1.000000000000000",
                "usd_price": "1264.710000000000036000"
            },
            "transaction": {
                "block_hash": "0x72caff4ac62d1890ed4a2726adb591f85576434870c6e87e78ebe22fc40d366f",
                "block_number": "16335379",
                "from_account": {
                    "user": {
                        "username": "wiegimania"
                    },
                    "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/21.png",
                    "address": "0xc2f3f03fd3b2e0ef7990013efe9f29296ffbd533",
                    "config": ""
                },
                "id": 932558069,
                "timestamp": "2023-01-04T19:00:59",
                "to_account": {
                    "user": null,
                    "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/11.png",
                    "address": "0x00000000006c3852cbef3e08e8df289169ede581",
                    "config": ""
                },
                "transaction_hash": "0xe3b9f061ca9f2e243be3f444aa195f349cc8a4472b41691399636059423d2ae6",
                "transaction_index": "84"
            },
            "created_date": "2023-01-04T19:01:01.296648",
            "quantity": "1",
            "approved_account": null,
            "bid_amount": null,
            "collection_slug": "pixawizards",
            "contract_address": "0x00000000006c3852cbef3e08e8df289169ede581",
            "custom_event_name": null,
            "dev_fee_payment_event": null,
            "dev_seller_fee_basis_points": 500,
            "duration": null,
            "ending_price": null,
            "from_account": null,
            "id": 9091742359,
            "is_private": false,
            "owner_account": null,
            "seller": {
                "user": {
                    "username": "cyprien"
                },
                "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/17.png",
                "address": "0x42a63047a1cd8449e3e70adeb7363c4ca01db528",
                "config": ""
            },
            "starting_price": null,
            "to_account": null,
            "winner_account": {
                "user": {
                    "username": "wiegimania"
                },
                "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/21.png",
                "address": "0xc2f3f03fd3b2e0ef7990013efe9f29296ffbd533",
                "config": ""
            },
            "listing_time": "2023-01-04T13:53:50"
        },
        {
            "asset": {
                "id": 18112165,
                "num_sales": 6,
                "background_color": null,
                "image_url": "https://i.seadn.io/gae/ithOq9w03co0J2bXSjTnlDHT_5Gc5vjE_NYaVQYop8tc4m-Qx7lyBYDo1ZXAY1cL-PSsLtbehQ_9DvzR8y1YjPNHRoOt9x1IUP50?w=500&auto=format",
                "image_preview_url": "https://i.seadn.io/gae/ithOq9w03co0J2bXSjTnlDHT_5Gc5vjE_NYaVQYop8tc4m-Qx7lyBYDo1ZXAY1cL-PSsLtbehQ_9DvzR8y1YjPNHRoOt9x1IUP50?w=500&auto=format",
                "image_thumbnail_url": "https://i.seadn.io/gae/ithOq9w03co0J2bXSjTnlDHT_5Gc5vjE_NYaVQYop8tc4m-Qx7lyBYDo1ZXAY1cL-PSsLtbehQ_9DvzR8y1YjPNHRoOt9x1IUP50?w=500&auto=format",
                "image_original_url": "https://ipfs.io/ipfs/QmYqzHNviLHAsrBFnTCm87NfSvB2t9EqcFEiU2Y2565RTf/image.gif",
                "animation_url": null,
                "animation_original_url": null,
                "name": "PixaWizard148",
                "description": "One of 1,000 PixaWizards. Made by PixaLyfe.",
                "external_link": "https://app.rarible.com/token/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0:158",
                "asset_contract": {
                    "address": "0xc6b0b290176aaab958441dcb0c64ad057cbc39a0",
                    "asset_contract_type": "non-fungible",
                    "created_date": "2021-02-14T05:14:04.847603",
                    "name": "PixaWizards",
                    "nft_version": "3.0",
                    "opensea_version": null,
                    "owner": 19357952,
                    "schema_name": "ERC721",
                    "symbol": "PWIZ",
                    "total_supply": "0",
                    "description": "A collection of 1,000 unique pixelated wizards.",
                    "external_link": "http://www.pixalyfe.com",
                    "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                    "default_to_fiat": false,
                    "dev_buyer_fee_basis_points": 0,
                    "dev_seller_fee_basis_points": 500,
                    "only_proxied_transfers": false,
                    "opensea_buyer_fee_basis_points": 0,
                    "opensea_seller_fee_basis_points": 250,
                    "buyer_fee_basis_points": 0,
                    "seller_fee_basis_points": 750,
                    "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c"
                },
                "permalink": "https://opensea.io/assets/ethereum/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0/158",
                "collection": {
                    "banner_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                    "chat_url": null,
                    "created_date": "2021-02-17T11:34:32.953650+00:00",
                    "default_to_fiat": false,
                    "description": "A collection of 1,000 unique pixelated wizards.",
                    "dev_buyer_fee_basis_points": "0",
                    "dev_seller_fee_basis_points": "500",
                    "discord_url": "https://discord.gg/invite/mj2uxev38D",
                    "display_data": {
                        "card_display_style": "contain"
                    },
                    "external_url": "http://www.pixalyfe.com",
                    "featured": false,
                    "featured_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                    "hidden": false,
                    "safelist_request_status": "verified",
                    "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                    "is_subject_to_whitelist": false,
                    "large_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                    "medium_username": null,
                    "name": "PixaWizards",
                    "only_proxied_transfers": false,
                    "opensea_buyer_fee_basis_points": "0",
                    "opensea_seller_fee_basis_points": "250",
                    "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c",
                    "require_email": false,
                    "short_description": null,
                    "slug": "pixawizards",
                    "telegram_url": null,
                    "twitter_username": "pixa_nft",
                    "instagram_username": "pixalyfe",
                    "wiki_url": null,
                    "is_nsfw": false,
                    "fees": {
                        "seller_fees": {
                            "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c": 500
                        },
                        "opensea_fees": {
                            "0x0000a26b00c1f0df003000390027140000faa719": 250
                        }
                    },
                    "is_rarity_enabled": true
                },
                "decimals": 0,
                "token_metadata": "https://ipfs.io/ipfs/QmXp4BocDKgHCBMfik9QHK4RWzFVmBk2CHm1WohiRdnhKL",
                "is_nsfw": false,
                "owner": null,
                "token_id": "158"
            },
            "asset_bundle": null,
            "event_type": "successful",
            "event_timestamp": "2023-01-02T09:35:35",
            "auction_type": null,
            "total_price": "40000000000000000",
            "payment_token": {
                "symbol": "ETH",
                "address": "0x0000000000000000000000000000000000000000",
                "image_url": "https://openseauserdata.com/files/6f8e2979d428180222796ff4a33ab929.svg",
                "name": "Ether",
                "decimals": 18,
                "eth_price": "1.000000000000000",
                "usd_price": "1264.710000000000036000"
            },
            "transaction": {
                "block_hash": "0xabd4489ebecd2b292e6dec065d9dee6a16f82227917d290f08ee3ae1dec2193e",
                "block_number": "16318229",
                "from_account": {
                    "user": {
                        "username": null
                    },
                    "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/28.png",
                    "address": "0x9498af223fa03a0ea9247bfb330600eec2ddc23b",
                    "config": ""
                },
                "id": 915489738,
                "timestamp": "2023-01-02T09:35:35",
                "to_account": {
                    "user": null,
                    "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/11.png",
                    "address": "0x00000000006c3852cbef3e08e8df289169ede581",
                    "config": ""
                },
                "transaction_hash": "0xe9b90a77863ea500af97f25d3836abada36c85774c9e77b16ab37b7543b1be58",
                "transaction_index": "45"
            },
            "created_date": "2023-01-02T09:35:37.180163",
            "quantity": "1",
            "approved_account": null,
            "bid_amount": null,
            "collection_slug": "pixawizards",
            "contract_address": "0x00000000006c3852cbef3e08e8df289169ede581",
            "custom_event_name": null,
            "dev_fee_payment_event": null,
            "dev_seller_fee_basis_points": 500,
            "duration": null,
            "ending_price": null,
            "from_account": null,
            "id": 9051159678,
            "is_private": false,
            "owner_account": null,
            "seller": {
                "user": {
                    "username": "ArrntVault"
                },
                "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/33.png",
                "address": "0xaf469a082a6cf6f96bc35157bef3a3c52baf2c14",
                "config": ""
            },
            "starting_price": null,
            "to_account": null,
            "winner_account": {
                "user": {
                    "username": null
                },
                "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/28.png",
                "address": "0x9498af223fa03a0ea9247bfb330600eec2ddc23b",
                "config": ""
            },
            "listing_time": "2022-10-23T18:14:54"
        },
        {
            "asset": {
                "id": 18660391,
                "num_sales": 3,
                "background_color": null,
                "image_url": "https://i.seadn.io/gae/nvFcL0msAayaPvYgHWnFGZeQc5syWSBAhB1U5gtsINpODsKCtiNOdCzoVbrTjMvck3h4HHDB_Mtu_-LwbYy2k9VFg817ag-vhxALXw?w=500&auto=format",
                "image_preview_url": "https://i.seadn.io/gae/nvFcL0msAayaPvYgHWnFGZeQc5syWSBAhB1U5gtsINpODsKCtiNOdCzoVbrTjMvck3h4HHDB_Mtu_-LwbYy2k9VFg817ag-vhxALXw?w=500&auto=format",
                "image_thumbnail_url": "https://i.seadn.io/gae/nvFcL0msAayaPvYgHWnFGZeQc5syWSBAhB1U5gtsINpODsKCtiNOdCzoVbrTjMvck3h4HHDB_Mtu_-LwbYy2k9VFg817ag-vhxALXw?w=500&auto=format",
                "image_original_url": "https://ipfs.io/ipfs/QmNjr1ZjaTC2Jx1yT55wMrUgaZ5AqvQsxGSNZHWxFnA4Ct/image.gif",
                "animation_url": null,
                "animation_original_url": null,
                "name": "PixaWizard591",
                "description": "One of 1,000 PixaWizards. Made by PixaLyfe.",
                "external_link": "https://app.rarible.com/token/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0:638",
                "asset_contract": {
                    "address": "0xc6b0b290176aaab958441dcb0c64ad057cbc39a0",
                    "asset_contract_type": "non-fungible",
                    "created_date": "2021-02-14T05:14:04.847603",
                    "name": "PixaWizards",
                    "nft_version": "3.0",
                    "opensea_version": null,
                    "owner": 19357952,
                    "schema_name": "ERC721",
                    "symbol": "PWIZ",
                    "total_supply": "0",
                    "description": "A collection of 1,000 unique pixelated wizards.",
                    "external_link": "http://www.pixalyfe.com",
                    "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                    "default_to_fiat": false,
                    "dev_buyer_fee_basis_points": 0,
                    "dev_seller_fee_basis_points": 500,
                    "only_proxied_transfers": false,
                    "opensea_buyer_fee_basis_points": 0,
                    "opensea_seller_fee_basis_points": 250,
                    "buyer_fee_basis_points": 0,
                    "seller_fee_basis_points": 750,
                    "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c"
                },
                "permalink": "https://opensea.io/assets/ethereum/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0/638",
                "collection": {
                    "banner_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                    "chat_url": null,
                    "created_date": "2021-02-17T11:34:32.953650+00:00",
                    "default_to_fiat": false,
                    "description": "A collection of 1,000 unique pixelated wizards.",
                    "dev_buyer_fee_basis_points": "0",
                    "dev_seller_fee_basis_points": "500",
                    "discord_url": "https://discord.gg/invite/mj2uxev38D",
                    "display_data": {
                        "card_display_style": "contain"
                    },
                    "external_url": "http://www.pixalyfe.com",
                    "featured": false,
                    "featured_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                    "hidden": false,
                    "safelist_request_status": "verified",
                    "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                    "is_subject_to_whitelist": false,
                    "large_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                    "medium_username": null,
                    "name": "PixaWizards",
                    "only_proxied_transfers": false,
                    "opensea_buyer_fee_basis_points": "0",
                    "opensea_seller_fee_basis_points": "250",
                    "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c",
                    "require_email": false,
                    "short_description": null,
                    "slug": "pixawizards",
                    "telegram_url": null,
                    "twitter_username": "pixa_nft",
                    "instagram_username": "pixalyfe",
                    "wiki_url": null,
                    "is_nsfw": false,
                    "fees": {
                        "seller_fees": {
                            "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c": 500
                        },
                        "opensea_fees": {
                            "0x0000a26b00c1f0df003000390027140000faa719": 250
                        }
                    },
                    "is_rarity_enabled": true
                },
                "decimals": 0,
                "token_metadata": "https://ipfs.io/ipfs/QmbsMwqyZTjYQAC9YmndsywNb1eH7ZHCwyLzuFJ3bo9Hsy",
                "is_nsfw": false,
                "owner": null,
                "token_id": "638"
            },
            "asset_bundle": null,
            "event_type": "successful",
            "event_timestamp": "2023-01-01T02:29:11",
            "auction_type": null,
            "total_price": "20000000000000000",
            "payment_token": {
                "symbol": "ETH",
                "address": "0x0000000000000000000000000000000000000000",
                "image_url": "https://openseauserdata.com/files/6f8e2979d428180222796ff4a33ab929.svg",
                "name": "Ether",
                "decimals": 18,
                "eth_price": "1.000000000000000",
                "usd_price": "1264.710000000000036000"
            },
            "transaction": {
                "block_hash": "0x9cee382ff984bf82bb5f8b0095e67699b832a446571c4ba9af8e2794636290db",
                "block_number": "16308931",
                "from_account": {
                    "user": {
                        "username": "ezincrypto"
                    },
                    "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/25.png",
                    "address": "0xfab9a3d37999e12252b47468d2ffd4be15936012",
                    "config": "affiliate"
                },
                "id": 912677953,
                "timestamp": "2023-01-01T02:29:11",
                "to_account": {
                    "user": null,
                    "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/11.png",
                    "address": "0x00000000006c3852cbef3e08e8df289169ede581",
                    "config": ""
                },
                "transaction_hash": "0x8d618abf3e6170916b0a1fdaa62a2a922811ec43c96c9e562258f265227b771b",
                "transaction_index": "78"
            },
            "created_date": "2023-01-01T02:29:13.663167",
            "quantity": "1",
            "approved_account": null,
            "bid_amount": null,
            "collection_slug": "pixawizards",
            "contract_address": "0x00000000006c3852cbef3e08e8df289169ede581",
            "custom_event_name": null,
            "dev_fee_payment_event": null,
            "dev_seller_fee_basis_points": 500,
            "duration": null,
            "ending_price": null,
            "from_account": null,
            "id": 9033330733,
            "is_private": false,
            "owner_account": null,
            "seller": {
                "user": {
                    "username": "UndrCutBot"
                },
                "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/4.png",
                "address": "0x5f7bbac91533023be41bb59cca34700f30ec6bcd",
                "config": ""
            },
            "starting_price": null,
            "to_account": null,
            "winner_account": {
                "user": {
                    "username": "ezincrypto"
                },
                "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/25.png",
                "address": "0xfab9a3d37999e12252b47468d2ffd4be15936012",
                "config": "affiliate"
            },
            "listing_time": "2022-12-28T20:20:30"
        },
        {
            "asset": null,
            "asset_bundle": {
                "assets": [
                    {
                        "id": 18210644,
                        "num_sales": 2,
                        "background_color": null,
                        "image_url": "https://i.seadn.io/gae/dRIwrmagWuUm9h06LwG6UH4YD7v8YGMT-LgYgvCwO1YRmlyP5Un6qMseCMFb3q-O1zmVTM9DrDIjjeAFzHRU4UnrHO0BI6zEJ0Zmpw?w=500&auto=format",
                        "image_preview_url": "https://i.seadn.io/gae/dRIwrmagWuUm9h06LwG6UH4YD7v8YGMT-LgYgvCwO1YRmlyP5Un6qMseCMFb3q-O1zmVTM9DrDIjjeAFzHRU4UnrHO0BI6zEJ0Zmpw?w=500&auto=format",
                        "image_thumbnail_url": "https://i.seadn.io/gae/dRIwrmagWuUm9h06LwG6UH4YD7v8YGMT-LgYgvCwO1YRmlyP5Un6qMseCMFb3q-O1zmVTM9DrDIjjeAFzHRU4UnrHO0BI6zEJ0Zmpw?w=500&auto=format",
                        "image_original_url": "https://ipfs.io/ipfs/QmZ6dfRuRbVFGkZ6saBStR7LVyyCQiZ6XDirVLub3JfyUQ/image.gif",
                        "animation_url": null,
                        "animation_original_url": null,
                        "name": "PixaWizard309",
                        "description": "One of 1,000 PixaWizards. Made by PixaLyfe.",
                        "external_link": "https://app.rarible.com/token/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0:325",
                        "asset_contract": {
                            "address": "0xc6b0b290176aaab958441dcb0c64ad057cbc39a0",
                            "asset_contract_type": "non-fungible",
                            "created_date": "2021-02-14T05:14:04.847603",
                            "name": "PixaWizards",
                            "nft_version": "3.0",
                            "opensea_version": null,
                            "owner": 19357952,
                            "schema_name": "ERC721",
                            "symbol": "PWIZ",
                            "total_supply": "0",
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "external_link": "http://www.pixalyfe.com",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "default_to_fiat": false,
                            "dev_buyer_fee_basis_points": 0,
                            "dev_seller_fee_basis_points": 500,
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": 0,
                            "opensea_seller_fee_basis_points": 250,
                            "buyer_fee_basis_points": 0,
                            "seller_fee_basis_points": 750,
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c"
                        },
                        "permalink": "https://opensea.io/assets/ethereum/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0/325",
                        "collection": {
                            "banner_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "chat_url": null,
                            "created_date": "2021-02-17T11:34:32.953650+00:00",
                            "default_to_fiat": false,
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "dev_buyer_fee_basis_points": "0",
                            "dev_seller_fee_basis_points": "500",
                            "discord_url": "https://discord.gg/invite/mj2uxev38D",
                            "display_data": {
                                "card_display_style": "contain"
                            },
                            "external_url": "http://www.pixalyfe.com",
                            "featured": false,
                            "featured_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "hidden": false,
                            "safelist_request_status": "verified",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "is_subject_to_whitelist": false,
                            "large_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "medium_username": null,
                            "name": "PixaWizards",
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": "0",
                            "opensea_seller_fee_basis_points": "250",
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c",
                            "require_email": false,
                            "short_description": null,
                            "slug": "pixawizards",
                            "telegram_url": null,
                            "twitter_username": "PixaLyfe",
                            "instagram_username": "pixalyfe",
                            "wiki_url": null,
                            "is_nsfw": false,
                            "fees": {
                                "seller_fees": {
                                    "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c": 500
                                },
                                "opensea_fees": {
                                    "0x0000a26b00c1f0df003000390027140000faa719": 250
                                }
                            },
                            "is_rarity_enabled": true
                        },
                        "decimals": 0,
                        "token_metadata": "https://ipfs.io/ipfs/QmeXNc8mg5TkxsUHpLu3UdwLTP4wWLJjtMK8eKrvmFY1N9",
                        "is_nsfw": false,
                        "owner": null,
                        "token_id": "325"
                    },
                    {
                        "id": 18227838,
                        "num_sales": 3,
                        "background_color": null,
                        "image_url": "https://i.seadn.io/gae/LMBOW-8gd3R0vf3dRS-mBsbuIvn0kMUv1La72jma72Is21qc-QrmwN4ut41gTbg1Q3t92xRT0Gzx6QpqJTTzswwnySUBASuCT1VIfb8?w=500&auto=format",
                        "image_preview_url": "https://i.seadn.io/gae/LMBOW-8gd3R0vf3dRS-mBsbuIvn0kMUv1La72jma72Is21qc-QrmwN4ut41gTbg1Q3t92xRT0Gzx6QpqJTTzswwnySUBASuCT1VIfb8?w=500&auto=format",
                        "image_thumbnail_url": "https://i.seadn.io/gae/LMBOW-8gd3R0vf3dRS-mBsbuIvn0kMUv1La72jma72Is21qc-QrmwN4ut41gTbg1Q3t92xRT0Gzx6QpqJTTzswwnySUBASuCT1VIfb8?w=500&auto=format",
                        "image_original_url": "https://ipfs.io/ipfs/QmYVf2twwmRYU5s1y8GxbxDFFsDbkqiusadbuiiin2bW2W/image.gif",
                        "animation_url": null,
                        "animation_original_url": null,
                        "name": "PixaWizard350",
                        "description": "One of 1,000 PixaWizards. Made by PixaLyfe.",
                        "external_link": "https://app.rarible.com/token/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0:366",
                        "asset_contract": {
                            "address": "0xc6b0b290176aaab958441dcb0c64ad057cbc39a0",
                            "asset_contract_type": "non-fungible",
                            "created_date": "2021-02-14T05:14:04.847603",
                            "name": "PixaWizards",
                            "nft_version": "3.0",
                            "opensea_version": null,
                            "owner": 19357952,
                            "schema_name": "ERC721",
                            "symbol": "PWIZ",
                            "total_supply": "0",
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "external_link": "http://www.pixalyfe.com",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "default_to_fiat": false,
                            "dev_buyer_fee_basis_points": 0,
                            "dev_seller_fee_basis_points": 500,
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": 0,
                            "opensea_seller_fee_basis_points": 250,
                            "buyer_fee_basis_points": 0,
                            "seller_fee_basis_points": 750,
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c"
                        },
                        "permalink": "https://opensea.io/assets/ethereum/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0/366",
                        "collection": {
                            "banner_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "chat_url": null,
                            "created_date": "2021-02-17T11:34:32.953650+00:00",
                            "default_to_fiat": false,
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "dev_buyer_fee_basis_points": "0",
                            "dev_seller_fee_basis_points": "500",
                            "discord_url": "https://discord.gg/invite/mj2uxev38D",
                            "display_data": {
                                "card_display_style": "contain"
                            },
                            "external_url": "http://www.pixalyfe.com",
                            "featured": false,
                            "featured_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "hidden": false,
                            "safelist_request_status": "verified",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "is_subject_to_whitelist": false,
                            "large_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "medium_username": null,
                            "name": "PixaWizards",
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": "0",
                            "opensea_seller_fee_basis_points": "250",
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c",
                            "require_email": false,
                            "short_description": null,
                            "slug": "pixawizards",
                            "telegram_url": null,
                            "twitter_username": "PixaLyfe",
                            "instagram_username": "pixalyfe",
                            "wiki_url": null,
                            "is_nsfw": false,
                            "fees": {
                                "seller_fees": {
                                    "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c": 500
                                },
                                "opensea_fees": {
                                    "0x0000a26b00c1f0df003000390027140000faa719": 250
                                }
                            },
                            "is_rarity_enabled": true
                        },
                        "decimals": 0,
                        "token_metadata": "https://ipfs.io/ipfs/QmRExWLKGnAnFeLB45iEuraZ2pbwepiHUC1HKojzkqMV6R",
                        "is_nsfw": false,
                        "owner": null,
                        "token_id": "366"
                    },
                    {
                        "id": 18279640,
                        "num_sales": 3,
                        "background_color": null,
                        "image_url": "https://i.seadn.io/gae/BZeho6_KKbYVuH1WjZ5MzxXAYMGtOqoUX78wU5XLcpygwNQKTwhV0GBvaQr-ulNjcy1sJbTlzFJGPN0r5AtfBWApsrd_wHLcLiV5HqA?w=500&auto=format",
                        "image_preview_url": "https://i.seadn.io/gae/BZeho6_KKbYVuH1WjZ5MzxXAYMGtOqoUX78wU5XLcpygwNQKTwhV0GBvaQr-ulNjcy1sJbTlzFJGPN0r5AtfBWApsrd_wHLcLiV5HqA?w=500&auto=format",
                        "image_thumbnail_url": "https://i.seadn.io/gae/BZeho6_KKbYVuH1WjZ5MzxXAYMGtOqoUX78wU5XLcpygwNQKTwhV0GBvaQr-ulNjcy1sJbTlzFJGPN0r5AtfBWApsrd_wHLcLiV5HqA?w=500&auto=format",
                        "image_original_url": "https://ipfs.io/ipfs/QmTgMWDhyUdd7JKZrhw14zEZQbZa5Z9bJSX3nyiLe7NhVj/image.gif",
                        "animation_url": null,
                        "animation_original_url": null,
                        "name": "PixaWizard447",
                        "description": "One of 1,000 PixaWizards. Made by PixaLyfe.",
                        "external_link": "https://app.rarible.com/token/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0:467",
                        "asset_contract": {
                            "address": "0xc6b0b290176aaab958441dcb0c64ad057cbc39a0",
                            "asset_contract_type": "non-fungible",
                            "created_date": "2021-02-14T05:14:04.847603",
                            "name": "PixaWizards",
                            "nft_version": "3.0",
                            "opensea_version": null,
                            "owner": 19357952,
                            "schema_name": "ERC721",
                            "symbol": "PWIZ",
                            "total_supply": "0",
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "external_link": "http://www.pixalyfe.com",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "default_to_fiat": false,
                            "dev_buyer_fee_basis_points": 0,
                            "dev_seller_fee_basis_points": 500,
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": 0,
                            "opensea_seller_fee_basis_points": 250,
                            "buyer_fee_basis_points": 0,
                            "seller_fee_basis_points": 750,
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c"
                        },
                        "permalink": "https://opensea.io/assets/ethereum/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0/467",
                        "collection": {
                            "banner_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "chat_url": null,
                            "created_date": "2021-02-17T11:34:32.953650+00:00",
                            "default_to_fiat": false,
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "dev_buyer_fee_basis_points": "0",
                            "dev_seller_fee_basis_points": "500",
                            "discord_url": "https://discord.gg/invite/mj2uxev38D",
                            "display_data": {
                                "card_display_style": "contain"
                            },
                            "external_url": "http://www.pixalyfe.com",
                            "featured": false,
                            "featured_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "hidden": false,
                            "safelist_request_status": "verified",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "is_subject_to_whitelist": false,
                            "large_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "medium_username": null,
                            "name": "PixaWizards",
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": "0",
                            "opensea_seller_fee_basis_points": "250",
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c",
                            "require_email": false,
                            "short_description": null,
                            "slug": "pixawizards",
                            "telegram_url": null,
                            "twitter_username": "PixaLyfe",
                            "instagram_username": "pixalyfe",
                            "wiki_url": null,
                            "is_nsfw": false,
                            "fees": {
                                "seller_fees": {
                                    "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c": 500
                                },
                                "opensea_fees": {
                                    "0x0000a26b00c1f0df003000390027140000faa719": 250
                                }
                            },
                            "is_rarity_enabled": true
                        },
                        "decimals": 0,
                        "token_metadata": "https://ipfs.io/ipfs/QmUGA1YmGbpHCsdtTpiniA9vkP4W4hGG2hdJdpVskoqbtY",
                        "is_nsfw": false,
                        "owner": null,
                        "token_id": "467"
                    }
                ],
                "maker": null,
                "slug": "wizards-6yB",
                "name": "Wizards",
                "description": null,
                "external_link": null,
                "asset_contract": {
                    "address": "0xc6b0b290176aaab958441dcb0c64ad057cbc39a0",
                    "asset_contract_type": "non-fungible",
                    "created_date": "2021-02-14T05:14:04.847603",
                    "name": "PixaWizards",
                    "nft_version": "3.0",
                    "opensea_version": null,
                    "owner": 19357952,
                    "schema_name": "ERC721",
                    "symbol": "PWIZ",
                    "total_supply": "0",
                    "description": "A collection of 1,000 unique pixelated wizards.",
                    "external_link": "http://www.pixalyfe.com",
                    "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                    "default_to_fiat": false,
                    "dev_buyer_fee_basis_points": 0,
                    "dev_seller_fee_basis_points": 500,
                    "only_proxied_transfers": false,
                    "opensea_buyer_fee_basis_points": 0,
                    "opensea_seller_fee_basis_points": 250,
                    "buyer_fee_basis_points": 0,
                    "seller_fee_basis_points": 750,
                    "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c"
                },
                "permalink": "https://opensea.io/bundles/wizards-6yB",
                "seaport_sell_orders": null
            },
            "event_type": "successful",
            "event_timestamp": "2022-12-29T17:11:35",
            "auction_type": null,
            "total_price": "100000000000000000",
            "payment_token": {
                "symbol": "ETH",
                "address": "0x0000000000000000000000000000000000000000",
                "image_url": "https://openseauserdata.com/files/6f8e2979d428180222796ff4a33ab929.svg",
                "name": "Ether",
                "decimals": 18,
                "eth_price": "1.000000000000000",
                "usd_price": "1264.710000000000036000"
            },
            "transaction": {
                "block_hash": "0x1d3b1dfd7608f46fbc8f70bc75b076b2e19d492c8996457567f9e0a816d9be92",
                "block_number": "16291823",
                "from_account": {
                    "user": {
                        "username": "jonybeevault"
                    },
                    "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/28.png",
                    "address": "0xb3a4d18a160e1e96e704785e655c245ee649fb90",
                    "config": ""
                },
                "id": 906629974,
                "timestamp": "2022-12-29T17:11:35",
                "to_account": {
                    "user": null,
                    "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/11.png",
                    "address": "0x00000000006c3852cbef3e08e8df289169ede581",
                    "config": ""
                },
                "transaction_hash": "0xf64f7aeb93983ae08d5ab916c096fabcf5259b7eabd7563f0123f58bf3ddac71",
                "transaction_index": "60"
            },
            "created_date": "2022-12-29T17:11:58.123304",
            "quantity": "1",
            "approved_account": null,
            "bid_amount": null,
            "collection_slug": "pixawizards",
            "contract_address": "0x00000000006c3852cbef3e08e8df289169ede581",
            "custom_event_name": null,
            "dev_fee_payment_event": null,
            "dev_seller_fee_basis_points": 500,
            "duration": null,
            "ending_price": null,
            "from_account": null,
            "id": 8998914294,
            "is_private": true,
            "owner_account": null,
            "seller": {
                "user": {
                    "username": "JonathanLittleVault"
                },
                "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/31.png",
                "address": "0x6b6ae848f555f70944bc99d736fe29fcaecf8b23",
                "config": ""
            },
            "starting_price": null,
            "to_account": null,
            "winner_account": {
                "user": {
                    "username": "jonybeevault"
                },
                "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/28.png",
                "address": "0xb3a4d18a160e1e96e704785e655c245ee649fb90",
                "config": ""
            },
            "listing_time": "2022-12-28T01:31:43"
        },
        {
            "asset": null,
            "asset_bundle": {
                "assets": [
                    {
                        "id": 18202800,
                        "num_sales": 2,
                        "background_color": null,
                        "image_url": "https://i.seadn.io/gae/pbqIG13pMbM9sdT0-fmkocRfBWnFJx-ORYDc5j13Z7s-n3DFEzE0CSGA3i9jFXe8cbtqF3IjoeV8G0FHkczqADKbyRI40-o_aoQfM5o?w=500&auto=format",
                        "image_preview_url": "https://i.seadn.io/gae/pbqIG13pMbM9sdT0-fmkocRfBWnFJx-ORYDc5j13Z7s-n3DFEzE0CSGA3i9jFXe8cbtqF3IjoeV8G0FHkczqADKbyRI40-o_aoQfM5o?w=500&auto=format",
                        "image_thumbnail_url": "https://i.seadn.io/gae/pbqIG13pMbM9sdT0-fmkocRfBWnFJx-ORYDc5j13Z7s-n3DFEzE0CSGA3i9jFXe8cbtqF3IjoeV8G0FHkczqADKbyRI40-o_aoQfM5o?w=500&auto=format",
                        "image_original_url": "https://ipfs.io/ipfs/Qmf3rn5kt8VMSKdHHnbbUFkuenSEjP1ZEXLvW76XadLGTn/image.gif",
                        "animation_url": null,
                        "animation_original_url": null,
                        "name": "PixaWizard293",
                        "description": "One of 1,000 PixaWizards. Made by PixaLyfe.",
                        "external_link": "https://app.rarible.com/token/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0:309",
                        "asset_contract": {
                            "address": "0xc6b0b290176aaab958441dcb0c64ad057cbc39a0",
                            "asset_contract_type": "non-fungible",
                            "created_date": "2021-02-14T05:14:04.847603",
                            "name": "PixaWizards",
                            "nft_version": "3.0",
                            "opensea_version": null,
                            "owner": 19357952,
                            "schema_name": "ERC721",
                            "symbol": "PWIZ",
                            "total_supply": "0",
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "external_link": "http://www.pixalyfe.com",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "default_to_fiat": false,
                            "dev_buyer_fee_basis_points": 0,
                            "dev_seller_fee_basis_points": 500,
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": 0,
                            "opensea_seller_fee_basis_points": 250,
                            "buyer_fee_basis_points": 0,
                            "seller_fee_basis_points": 750,
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c"
                        },
                        "permalink": "https://opensea.io/assets/ethereum/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0/309",
                        "collection": {
                            "banner_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "chat_url": null,
                            "created_date": "2021-02-17T11:34:32.953650+00:00",
                            "default_to_fiat": false,
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "dev_buyer_fee_basis_points": "0",
                            "dev_seller_fee_basis_points": "500",
                            "discord_url": "https://discord.gg/invite/mj2uxev38D",
                            "display_data": {
                                "card_display_style": "contain"
                            },
                            "external_url": "http://www.pixalyfe.com",
                            "featured": false,
                            "featured_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "hidden": false,
                            "safelist_request_status": "verified",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "is_subject_to_whitelist": false,
                            "large_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "medium_username": null,
                            "name": "PixaWizards",
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": "0",
                            "opensea_seller_fee_basis_points": "250",
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c",
                            "require_email": false,
                            "short_description": null,
                            "slug": "pixawizards",
                            "telegram_url": null,
                            "twitter_username": "PixaLyfe",
                            "instagram_username": "pixalyfe",
                            "wiki_url": null,
                            "is_nsfw": false,
                            "fees": {
                                "seller_fees": {
                                    "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c": 500
                                },
                                "opensea_fees": {
                                    "0x0000a26b00c1f0df003000390027140000faa719": 250
                                }
                            },
                            "is_rarity_enabled": true
                        },
                        "decimals": 0,
                        "token_metadata": "https://ipfs.io/ipfs/QmQfwxw2EhfRsYzCd4qJeBp1CZLNrrvEfaw1gQCVzTw73P",
                        "is_nsfw": false,
                        "owner": null,
                        "token_id": "309"
                    },
                    {
                        "id": 18660391,
                        "num_sales": 3,
                        "background_color": null,
                        "image_url": "https://i.seadn.io/gae/nvFcL0msAayaPvYgHWnFGZeQc5syWSBAhB1U5gtsINpODsKCtiNOdCzoVbrTjMvck3h4HHDB_Mtu_-LwbYy2k9VFg817ag-vhxALXw?w=500&auto=format",
                        "image_preview_url": "https://i.seadn.io/gae/nvFcL0msAayaPvYgHWnFGZeQc5syWSBAhB1U5gtsINpODsKCtiNOdCzoVbrTjMvck3h4HHDB_Mtu_-LwbYy2k9VFg817ag-vhxALXw?w=500&auto=format",
                        "image_thumbnail_url": "https://i.seadn.io/gae/nvFcL0msAayaPvYgHWnFGZeQc5syWSBAhB1U5gtsINpODsKCtiNOdCzoVbrTjMvck3h4HHDB_Mtu_-LwbYy2k9VFg817ag-vhxALXw?w=500&auto=format",
                        "image_original_url": "https://ipfs.io/ipfs/QmNjr1ZjaTC2Jx1yT55wMrUgaZ5AqvQsxGSNZHWxFnA4Ct/image.gif",
                        "animation_url": null,
                        "animation_original_url": null,
                        "name": "PixaWizard591",
                        "description": "One of 1,000 PixaWizards. Made by PixaLyfe.",
                        "external_link": "https://app.rarible.com/token/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0:638",
                        "asset_contract": {
                            "address": "0xc6b0b290176aaab958441dcb0c64ad057cbc39a0",
                            "asset_contract_type": "non-fungible",
                            "created_date": "2021-02-14T05:14:04.847603",
                            "name": "PixaWizards",
                            "nft_version": "3.0",
                            "opensea_version": null,
                            "owner": 19357952,
                            "schema_name": "ERC721",
                            "symbol": "PWIZ",
                            "total_supply": "0",
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "external_link": "http://www.pixalyfe.com",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "default_to_fiat": false,
                            "dev_buyer_fee_basis_points": 0,
                            "dev_seller_fee_basis_points": 500,
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": 0,
                            "opensea_seller_fee_basis_points": 250,
                            "buyer_fee_basis_points": 0,
                            "seller_fee_basis_points": 750,
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c"
                        },
                        "permalink": "https://opensea.io/assets/ethereum/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0/638",
                        "collection": {
                            "banner_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "chat_url": null,
                            "created_date": "2021-02-17T11:34:32.953650+00:00",
                            "default_to_fiat": false,
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "dev_buyer_fee_basis_points": "0",
                            "dev_seller_fee_basis_points": "500",
                            "discord_url": "https://discord.gg/invite/mj2uxev38D",
                            "display_data": {
                                "card_display_style": "contain"
                            },
                            "external_url": "http://www.pixalyfe.com",
                            "featured": false,
                            "featured_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "hidden": false,
                            "safelist_request_status": "verified",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "is_subject_to_whitelist": false,
                            "large_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "medium_username": null,
                            "name": "PixaWizards",
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": "0",
                            "opensea_seller_fee_basis_points": "250",
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c",
                            "require_email": false,
                            "short_description": null,
                            "slug": "pixawizards",
                            "telegram_url": null,
                            "twitter_username": "PixaLyfe",
                            "instagram_username": "pixalyfe",
                            "wiki_url": null,
                            "is_nsfw": false,
                            "fees": {
                                "seller_fees": {
                                    "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c": 500
                                },
                                "opensea_fees": {
                                    "0x0000a26b00c1f0df003000390027140000faa719": 250
                                }
                            },
                            "is_rarity_enabled": true
                        },
                        "decimals": 0,
                        "token_metadata": "https://ipfs.io/ipfs/QmbsMwqyZTjYQAC9YmndsywNb1eH7ZHCwyLzuFJ3bo9Hsy",
                        "is_nsfw": false,
                        "owner": null,
                        "token_id": "638"
                    },
                    {
                        "id": 19176513,
                        "num_sales": 2,
                        "background_color": null,
                        "image_url": "https://i.seadn.io/gae/C3A-sfTllURU2mCR-uiOEweac5HDgV55OgC0-LbmZ284tKQZdg1gHDE2nWoRPKg1tbVUqgRDJ6kJlpql8s2gVJONZnJ8UZLEyebz?w=500&auto=format",
                        "image_preview_url": "https://i.seadn.io/gae/C3A-sfTllURU2mCR-uiOEweac5HDgV55OgC0-LbmZ284tKQZdg1gHDE2nWoRPKg1tbVUqgRDJ6kJlpql8s2gVJONZnJ8UZLEyebz?w=500&auto=format",
                        "image_thumbnail_url": "https://i.seadn.io/gae/C3A-sfTllURU2mCR-uiOEweac5HDgV55OgC0-LbmZ284tKQZdg1gHDE2nWoRPKg1tbVUqgRDJ6kJlpql8s2gVJONZnJ8UZLEyebz?w=500&auto=format",
                        "image_original_url": "https://ipfs.io/ipfs/QmSisUN23iq7wg3aBJpXJvFLQYiPcUmgKQkhkhVNywDPsS/image.gif",
                        "animation_url": null,
                        "animation_original_url": null,
                        "name": "PixaWizard786",
                        "description": "One of 1,000 PixaWizards. Made by PixaLyfe.",
                        "external_link": "https://rarible.com/token/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0:854",
                        "asset_contract": {
                            "address": "0xc6b0b290176aaab958441dcb0c64ad057cbc39a0",
                            "asset_contract_type": "non-fungible",
                            "created_date": "2021-02-14T05:14:04.847603",
                            "name": "PixaWizards",
                            "nft_version": "3.0",
                            "opensea_version": null,
                            "owner": 19357952,
                            "schema_name": "ERC721",
                            "symbol": "PWIZ",
                            "total_supply": "0",
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "external_link": "http://www.pixalyfe.com",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "default_to_fiat": false,
                            "dev_buyer_fee_basis_points": 0,
                            "dev_seller_fee_basis_points": 500,
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": 0,
                            "opensea_seller_fee_basis_points": 250,
                            "buyer_fee_basis_points": 0,
                            "seller_fee_basis_points": 750,
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c"
                        },
                        "permalink": "https://opensea.io/assets/ethereum/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0/854",
                        "collection": {
                            "banner_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "chat_url": null,
                            "created_date": "2021-02-17T11:34:32.953650+00:00",
                            "default_to_fiat": false,
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "dev_buyer_fee_basis_points": "0",
                            "dev_seller_fee_basis_points": "500",
                            "discord_url": "https://discord.gg/invite/mj2uxev38D",
                            "display_data": {
                                "card_display_style": "contain"
                            },
                            "external_url": "http://www.pixalyfe.com",
                            "featured": false,
                            "featured_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "hidden": false,
                            "safelist_request_status": "verified",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "is_subject_to_whitelist": false,
                            "large_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "medium_username": null,
                            "name": "PixaWizards",
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": "0",
                            "opensea_seller_fee_basis_points": "250",
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c",
                            "require_email": false,
                            "short_description": null,
                            "slug": "pixawizards",
                            "telegram_url": null,
                            "twitter_username": "PixaLyfe",
                            "instagram_username": "pixalyfe",
                            "wiki_url": null,
                            "is_nsfw": false,
                            "fees": {
                                "seller_fees": {
                                    "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c": 500
                                },
                                "opensea_fees": {
                                    "0x0000a26b00c1f0df003000390027140000faa719": 250
                                }
                            },
                            "is_rarity_enabled": true
                        },
                        "decimals": 0,
                        "token_metadata": "https://ipfs.io/ipfs/QmRhHgMSeiEzY1TniCA3VvVduxKTY53fEQbPbmKsTfDD1r",
                        "is_nsfw": false,
                        "owner": null,
                        "token_id": "854"
                    },
                    {
                        "id": 19207658,
                        "num_sales": 0,
                        "background_color": null,
                        "image_url": "https://i.seadn.io/gae/jfdM2Z8LdGe5vNeMEH8xhxu-8oXUEI9vNPy1d2C8pf0S5LVmGtTCAtfGs_Y-E9HSEN3L9ibFhEl2RGwdpz8np2B7AcaZqPMjoesF9N0?w=500&auto=format",
                        "image_preview_url": "https://i.seadn.io/gae/jfdM2Z8LdGe5vNeMEH8xhxu-8oXUEI9vNPy1d2C8pf0S5LVmGtTCAtfGs_Y-E9HSEN3L9ibFhEl2RGwdpz8np2B7AcaZqPMjoesF9N0?w=500&auto=format",
                        "image_thumbnail_url": "https://i.seadn.io/gae/jfdM2Z8LdGe5vNeMEH8xhxu-8oXUEI9vNPy1d2C8pf0S5LVmGtTCAtfGs_Y-E9HSEN3L9ibFhEl2RGwdpz8np2B7AcaZqPMjoesF9N0?w=500&auto=format",
                        "image_original_url": "https://ipfs.io/ipfs/QmQL2Ze9oAXUyRBVcTa1xi3WKnQxNx7qnkcyKk3jnWbTZ2/image.gif",
                        "animation_url": null,
                        "animation_original_url": null,
                        "name": "PixaWizard837",
                        "description": "One of 1,000 PixaWizards. Made by PixaLyfe.",
                        "external_link": "https://rarible.com/token/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0:907",
                        "asset_contract": {
                            "address": "0xc6b0b290176aaab958441dcb0c64ad057cbc39a0",
                            "asset_contract_type": "non-fungible",
                            "created_date": "2021-02-14T05:14:04.847603",
                            "name": "PixaWizards",
                            "nft_version": "3.0",
                            "opensea_version": null,
                            "owner": 19357952,
                            "schema_name": "ERC721",
                            "symbol": "PWIZ",
                            "total_supply": "0",
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "external_link": "http://www.pixalyfe.com",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "default_to_fiat": false,
                            "dev_buyer_fee_basis_points": 0,
                            "dev_seller_fee_basis_points": 500,
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": 0,
                            "opensea_seller_fee_basis_points": 250,
                            "buyer_fee_basis_points": 0,
                            "seller_fee_basis_points": 750,
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c"
                        },
                        "permalink": "https://opensea.io/assets/ethereum/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0/907",
                        "collection": {
                            "banner_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "chat_url": null,
                            "created_date": "2021-02-17T11:34:32.953650+00:00",
                            "default_to_fiat": false,
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "dev_buyer_fee_basis_points": "0",
                            "dev_seller_fee_basis_points": "500",
                            "discord_url": "https://discord.gg/invite/mj2uxev38D",
                            "display_data": {
                                "card_display_style": "contain"
                            },
                            "external_url": "http://www.pixalyfe.com",
                            "featured": false,
                            "featured_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "hidden": false,
                            "safelist_request_status": "verified",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "is_subject_to_whitelist": false,
                            "large_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "medium_username": null,
                            "name": "PixaWizards",
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": "0",
                            "opensea_seller_fee_basis_points": "250",
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c",
                            "require_email": false,
                            "short_description": null,
                            "slug": "pixawizards",
                            "telegram_url": null,
                            "twitter_username": "PixaLyfe",
                            "instagram_username": "pixalyfe",
                            "wiki_url": null,
                            "is_nsfw": false,
                            "fees": {
                                "seller_fees": {
                                    "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c": 500
                                },
                                "opensea_fees": {
                                    "0x0000a26b00c1f0df003000390027140000faa719": 250
                                }
                            },
                            "is_rarity_enabled": true
                        },
                        "decimals": 0,
                        "token_metadata": "https://ipfs.io/ipfs/QmNkCWnwKVRCZWzSp3H3AHpYDaLrcV2612cMvkwHA1gjqT",
                        "is_nsfw": false,
                        "owner": null,
                        "token_id": "907"
                    },
                    {
                        "id": 19261400,
                        "num_sales": 2,
                        "background_color": null,
                        "image_url": "https://i.seadn.io/gae/woRLZOEFzziYibLLATgvlp79n_7GGNe6eVIvt4wK4bKeGyPw837X0xUTBxIZ2PG4t531-OpBFnaiPTtmJsKZhIOIxRl_gTNg_GPB?w=500&auto=format",
                        "image_preview_url": "https://i.seadn.io/gae/woRLZOEFzziYibLLATgvlp79n_7GGNe6eVIvt4wK4bKeGyPw837X0xUTBxIZ2PG4t531-OpBFnaiPTtmJsKZhIOIxRl_gTNg_GPB?w=500&auto=format",
                        "image_thumbnail_url": "https://i.seadn.io/gae/woRLZOEFzziYibLLATgvlp79n_7GGNe6eVIvt4wK4bKeGyPw837X0xUTBxIZ2PG4t531-OpBFnaiPTtmJsKZhIOIxRl_gTNg_GPB?w=500&auto=format",
                        "image_original_url": "https://ipfs.io/ipfs/QmNScdJu13nKj6vd6gRbzQG4Ciuemk424gEoWDXwdAgNmh/image.gif",
                        "animation_url": null,
                        "animation_original_url": null,
                        "name": "PixaWizard868",
                        "description": "One of 1,000 PixaWizards. Made by PixaLyfe.",
                        "external_link": "https://rarible.com/token/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0:940",
                        "asset_contract": {
                            "address": "0xc6b0b290176aaab958441dcb0c64ad057cbc39a0",
                            "asset_contract_type": "non-fungible",
                            "created_date": "2021-02-14T05:14:04.847603",
                            "name": "PixaWizards",
                            "nft_version": "3.0",
                            "opensea_version": null,
                            "owner": 19357952,
                            "schema_name": "ERC721",
                            "symbol": "PWIZ",
                            "total_supply": "0",
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "external_link": "http://www.pixalyfe.com",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "default_to_fiat": false,
                            "dev_buyer_fee_basis_points": 0,
                            "dev_seller_fee_basis_points": 500,
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": 0,
                            "opensea_seller_fee_basis_points": 250,
                            "buyer_fee_basis_points": 0,
                            "seller_fee_basis_points": 750,
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c"
                        },
                        "permalink": "https://opensea.io/assets/ethereum/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0/940",
                        "collection": {
                            "banner_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "chat_url": null,
                            "created_date": "2021-02-17T11:34:32.953650+00:00",
                            "default_to_fiat": false,
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "dev_buyer_fee_basis_points": "0",
                            "dev_seller_fee_basis_points": "500",
                            "discord_url": "https://discord.gg/invite/mj2uxev38D",
                            "display_data": {
                                "card_display_style": "contain"
                            },
                            "external_url": "http://www.pixalyfe.com",
                            "featured": false,
                            "featured_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "hidden": false,
                            "safelist_request_status": "verified",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "is_subject_to_whitelist": false,
                            "large_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "medium_username": null,
                            "name": "PixaWizards",
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": "0",
                            "opensea_seller_fee_basis_points": "250",
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c",
                            "require_email": false,
                            "short_description": null,
                            "slug": "pixawizards",
                            "telegram_url": null,
                            "twitter_username": "PixaLyfe",
                            "instagram_username": "pixalyfe",
                            "wiki_url": null,
                            "is_nsfw": false,
                            "fees": {
                                "seller_fees": {
                                    "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c": 500
                                },
                                "opensea_fees": {
                                    "0x0000a26b00c1f0df003000390027140000faa719": 250
                                }
                            },
                            "is_rarity_enabled": true
                        },
                        "decimals": 0,
                        "token_metadata": "https://ipfs.io/ipfs/QmaoymwxyvaZk3FLE7Kw949Akmq37ybqYhSW6fSDZy8q7W",
                        "is_nsfw": false,
                        "owner": null,
                        "token_id": "940"
                    },
                    {
                        "id": 19345233,
                        "num_sales": 0,
                        "background_color": null,
                        "image_url": "https://i.seadn.io/gae/wFi7VUo4p0wOnnGjOqwHuecMU804zQyPv_FbbLumonFxk46QXlxTjvjRVZB0sn-7zfk_YoxUUslx-MB6YW60kkqjCpMyPRUCjZ5L?w=500&auto=format",
                        "image_preview_url": "https://i.seadn.io/gae/wFi7VUo4p0wOnnGjOqwHuecMU804zQyPv_FbbLumonFxk46QXlxTjvjRVZB0sn-7zfk_YoxUUslx-MB6YW60kkqjCpMyPRUCjZ5L?w=500&auto=format",
                        "image_thumbnail_url": "https://i.seadn.io/gae/wFi7VUo4p0wOnnGjOqwHuecMU804zQyPv_FbbLumonFxk46QXlxTjvjRVZB0sn-7zfk_YoxUUslx-MB6YW60kkqjCpMyPRUCjZ5L?w=500&auto=format",
                        "image_original_url": "https://ipfs.io/ipfs/QmStvbpgghQqVnGRVKbPos9KB7RaZ1TwqmFpP611kwS1YY/image.gif",
                        "animation_url": null,
                        "animation_original_url": null,
                        "name": "PixaWizard940",
                        "description": "One of 1,000 PixaWizards. Made by PixaLyfe.",
                        "external_link": "https://rarible.com/token/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0:1014",
                        "asset_contract": {
                            "address": "0xc6b0b290176aaab958441dcb0c64ad057cbc39a0",
                            "asset_contract_type": "non-fungible",
                            "created_date": "2021-02-14T05:14:04.847603",
                            "name": "PixaWizards",
                            "nft_version": "3.0",
                            "opensea_version": null,
                            "owner": 19357952,
                            "schema_name": "ERC721",
                            "symbol": "PWIZ",
                            "total_supply": "0",
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "external_link": "http://www.pixalyfe.com",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "default_to_fiat": false,
                            "dev_buyer_fee_basis_points": 0,
                            "dev_seller_fee_basis_points": 500,
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": 0,
                            "opensea_seller_fee_basis_points": 250,
                            "buyer_fee_basis_points": 0,
                            "seller_fee_basis_points": 750,
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c"
                        },
                        "permalink": "https://opensea.io/assets/ethereum/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0/1014",
                        "collection": {
                            "banner_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "chat_url": null,
                            "created_date": "2021-02-17T11:34:32.953650+00:00",
                            "default_to_fiat": false,
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "dev_buyer_fee_basis_points": "0",
                            "dev_seller_fee_basis_points": "500",
                            "discord_url": "https://discord.gg/invite/mj2uxev38D",
                            "display_data": {
                                "card_display_style": "contain"
                            },
                            "external_url": "http://www.pixalyfe.com",
                            "featured": false,
                            "featured_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "hidden": false,
                            "safelist_request_status": "verified",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "is_subject_to_whitelist": false,
                            "large_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "medium_username": null,
                            "name": "PixaWizards",
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": "0",
                            "opensea_seller_fee_basis_points": "250",
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c",
                            "require_email": false,
                            "short_description": null,
                            "slug": "pixawizards",
                            "telegram_url": null,
                            "twitter_username": "PixaLyfe",
                            "instagram_username": "pixalyfe",
                            "wiki_url": null,
                            "is_nsfw": false,
                            "fees": {
                                "seller_fees": {
                                    "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c": 500
                                },
                                "opensea_fees": {
                                    "0x0000a26b00c1f0df003000390027140000faa719": 250
                                }
                            },
                            "is_rarity_enabled": true
                        },
                        "decimals": 0,
                        "token_metadata": "https://ipfs.io/ipfs/QmVg9qNmgT4HA4cpssVKQ37jd9DRkB3sjg932rQ578WLvW",
                        "is_nsfw": false,
                        "owner": null,
                        "token_id": "1014"
                    },
                    {
                        "id": 19390616,
                        "num_sales": 2,
                        "background_color": null,
                        "image_url": "https://i.seadn.io/gae/H_JAA1_jtfzUbQZogCG328hb6Zimtk6xRkC3-PdaZDXTWFagg30t5JZr8CUucN833FooVOLCDz-4be22ycRitibWt9lqVvL_X48hhdM?w=500&auto=format",
                        "image_preview_url": "https://i.seadn.io/gae/H_JAA1_jtfzUbQZogCG328hb6Zimtk6xRkC3-PdaZDXTWFagg30t5JZr8CUucN833FooVOLCDz-4be22ycRitibWt9lqVvL_X48hhdM?w=500&auto=format",
                        "image_thumbnail_url": "https://i.seadn.io/gae/H_JAA1_jtfzUbQZogCG328hb6Zimtk6xRkC3-PdaZDXTWFagg30t5JZr8CUucN833FooVOLCDz-4be22ycRitibWt9lqVvL_X48hhdM?w=500&auto=format",
                        "image_original_url": "https://ipfs.io/ipfs/QmR2EtVjRJuTEMXZp3TY8b2RZB67VmrCwsWfML16kPX2b1/image.gif",
                        "animation_url": null,
                        "animation_original_url": null,
                        "name": "PixaWizard962",
                        "description": "One of 1,000 PixaWizards. Made by PixaLyfe.",
                        "external_link": "https://rarible.com/token/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0:1037",
                        "asset_contract": {
                            "address": "0xc6b0b290176aaab958441dcb0c64ad057cbc39a0",
                            "asset_contract_type": "non-fungible",
                            "created_date": "2021-02-14T05:14:04.847603",
                            "name": "PixaWizards",
                            "nft_version": "3.0",
                            "opensea_version": null,
                            "owner": 19357952,
                            "schema_name": "ERC721",
                            "symbol": "PWIZ",
                            "total_supply": "0",
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "external_link": "http://www.pixalyfe.com",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "default_to_fiat": false,
                            "dev_buyer_fee_basis_points": 0,
                            "dev_seller_fee_basis_points": 500,
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": 0,
                            "opensea_seller_fee_basis_points": 250,
                            "buyer_fee_basis_points": 0,
                            "seller_fee_basis_points": 750,
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c"
                        },
                        "permalink": "https://opensea.io/assets/ethereum/0xc6b0b290176aaab958441dcb0c64ad057cbc39a0/1037",
                        "collection": {
                            "banner_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "chat_url": null,
                            "created_date": "2021-02-17T11:34:32.953650+00:00",
                            "default_to_fiat": false,
                            "description": "A collection of 1,000 unique pixelated wizards.",
                            "dev_buyer_fee_basis_points": "0",
                            "dev_seller_fee_basis_points": "500",
                            "discord_url": "https://discord.gg/invite/mj2uxev38D",
                            "display_data": {
                                "card_display_style": "contain"
                            },
                            "external_url": "http://www.pixalyfe.com",
                            "featured": false,
                            "featured_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "hidden": false,
                            "safelist_request_status": "verified",
                            "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                            "is_subject_to_whitelist": false,
                            "large_image_url": "https://i.seadn.io/gae/PSVJwbAaDxxdpIpJalAFXHemyKubIG0gPZ-RpQawXpdDuxhKqhsDiAIGA1Iu8pfBJMJLwUOw8IO2vVZhDLnPVpgSRES_usHNEaeDk1s?w=500&auto=format",
                            "medium_username": null,
                            "name": "PixaWizards",
                            "only_proxied_transfers": false,
                            "opensea_buyer_fee_basis_points": "0",
                            "opensea_seller_fee_basis_points": "250",
                            "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c",
                            "require_email": false,
                            "short_description": null,
                            "slug": "pixawizards",
                            "telegram_url": null,
                            "twitter_username": "PixaLyfe",
                            "instagram_username": "pixalyfe",
                            "wiki_url": null,
                            "is_nsfw": false,
                            "fees": {
                                "seller_fees": {
                                    "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c": 500
                                },
                                "opensea_fees": {
                                    "0x0000a26b00c1f0df003000390027140000faa719": 250
                                }
                            },
                            "is_rarity_enabled": true
                        },
                        "decimals": 0,
                        "token_metadata": "https://ipfs.io/ipfs/QmcmdSZ14Y6Qzt5PAGhVFEnB8GZz2Rspjv7E19LgYU7AUG",
                        "is_nsfw": false,
                        "owner": null,
                        "token_id": "1037"
                    }
                ],
                "maker": null,
                "slug": "pixa-aBU",
                "name": "pixa",
                "description": null,
                "external_link": null,
                "asset_contract": {
                    "address": "0xc6b0b290176aaab958441dcb0c64ad057cbc39a0",
                    "asset_contract_type": "non-fungible",
                    "created_date": "2021-02-14T05:14:04.847603",
                    "name": "PixaWizards",
                    "nft_version": "3.0",
                    "opensea_version": null,
                    "owner": 19357952,
                    "schema_name": "ERC721",
                    "symbol": "PWIZ",
                    "total_supply": "0",
                    "description": "A collection of 1,000 unique pixelated wizards.",
                    "external_link": "http://www.pixalyfe.com",
                    "image_url": "https://i.seadn.io/gae/nwvYgwZp-ln5cix5p4r7axRPxhhAsgQrrOcaf5vVsxNBecjzRhXyRDkgd5m0ZO3SB7zzfAZNGZkIOFiNg4GlNmBrn0TLpe1pTp_PTAw?w=500&auto=format",
                    "default_to_fiat": false,
                    "dev_buyer_fee_basis_points": 0,
                    "dev_seller_fee_basis_points": 500,
                    "only_proxied_transfers": false,
                    "opensea_buyer_fee_basis_points": 0,
                    "opensea_seller_fee_basis_points": 250,
                    "buyer_fee_basis_points": 0,
                    "seller_fee_basis_points": 750,
                    "payout_address": "0x5c2b89cbec1a4996aa5e81f3dff8505abec6b34c"
                },
                "permalink": "https://opensea.io/bundles/pixa-aBU",
                "seaport_sell_orders": null
            },
            "event_type": "successful",
            "event_timestamp": "2022-12-28T20:18:35",
            "auction_type": null,
            "total_price": "1000000000000000",
            "payment_token": {
                "symbol": "ETH",
                "address": "0x0000000000000000000000000000000000000000",
                "image_url": "https://openseauserdata.com/files/6f8e2979d428180222796ff4a33ab929.svg",
                "name": "Ether",
                "decimals": 18,
                "eth_price": "1.000000000000000",
                "usd_price": "1264.710000000000036000"
            },
            "transaction": {
                "block_hash": "0x141e7ac08fb8eb5c03aad272b2b3e05f11e27d0e3164a040f57c6696d657c182",
                "block_number": "16285594",
                "from_account": {
                    "user": {
                        "username": "UndrCutBot"
                    },
                    "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/4.png",
                    "address": "0x5f7bbac91533023be41bb59cca34700f30ec6bcd",
                    "config": ""
                },
                "id": 904143423,
                "timestamp": "2022-12-28T20:18:35",
                "to_account": {
                    "user": null,
                    "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/11.png",
                    "address": "0x00000000006c3852cbef3e08e8df289169ede581",
                    "config": ""
                },
                "transaction_hash": "0x9ce83e73a43880664ec898b369d06c32812c82ff0b27a64ca297da4ce6dd5a42",
                "transaction_index": "114"
            },
            "created_date": "2022-12-28T20:18:38.397263",
            "quantity": "1",
            "approved_account": null,
            "bid_amount": null,
            "collection_slug": "pixawizards",
            "contract_address": "0x00000000006c3852cbef3e08e8df289169ede581",
            "custom_event_name": null,
            "dev_fee_payment_event": null,
            "dev_seller_fee_basis_points": 500,
            "duration": null,
            "ending_price": null,
            "from_account": null,
            "id": 8986193562,
            "is_private": false,
            "owner_account": null,
            "seller": {
                "user": {
                    "username": "0xA212b52f72B7"
                },
                "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/17.png",
                "address": "0xa212b52f72b7434cd8a8bc8f06c1e6b84afb7979",
                "config": ""
            },
            "starting_price": null,
            "to_account": null,
            "winner_account": {
                "user": {
                    "username": "UndrCutBot"
                },
                "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/4.png",
                "address": "0x5f7bbac91533023be41bb59cca34700f30ec6bcd",
                "config": ""
            },
            "listing_time": "2022-12-28T20:13:33"
        }
    ]
}
'''

data = json.loads(nft_string)

# print(type(data['asset_events']))

# for asset in data['asset_events']:
#     print(type(asset))
#     print(asset)
#     print("#####################################")
#     print("\n")


new_string = json.dumps(data, indent=2, sort_keys=True)
print(new_string)
 